version: '2'
services:
  #traefik:
  #image: traefik:v2.3
  #container_name: traefik
  #command:
  #- "--log.level=DEBUG"
  #- --api.insecure=true
  #- --providers.docker=true
  #- --providers.docker.exposedbydefault=false
  #- --entrypoints.web.address=:80
  #- --entrypoints.websecure.address=:443
  #ports:
  #- 80:80
  #- 8090:8080
  #volumes:
  #- /var/run/docker.sock:/var/run/docker.sock:ro
  #- /mnt/wsl/docker-desktop-data/version-pack-data/community/docker/volumes/traefik-data:/var/opt/password
  #labels:
  # Dashboard
  #- traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)
  #- traefik.http.routers.traefik.service=api@internal
  #- traefik.http.routers.traefik.tls.certresolver=leresolver
  #- traefik.http.routers.traefik.entrypoints=websecure
  #- traefik.http.routers.traefik.middlewares=authtraefik
  #- traefik.http.middlewares.authtraefik.basicauth.users=admin:$$apr1$$aoHWta1O$$PL9Zmo8oQVxhVp3KFU4jb/ # user/password

  jhdemo-sonar:
    image: sonarqube:8.3.1-community
    container_name:
      sonar
      #labels:
      #- traefik.enable=true
      #- traefik.http.routers.jhdemo-sonar.rule=Host(`localhost`)
      #- traefik.http.routers.jhdemo-sonar.entrypoints=web
      #- traefik.http.routers.jhdemo-sonar.middlewares=auth
      #- traefik.jhdemo-sonar.port=9000
      #- traefik.http.middlewares.auth.basicauth.usersfile=C:\\DEV\Workspaces\\ynov\\jhdemo\\src\\main\\docker\\sonarusers
    ports:
      - 9001:9000
      - 9092:9092
